apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hykuup-argo
  namespace: argocd
spec:
  destination:
    namespace: hykuup-knapsack-argo
    # Replace with "in-cluster" for local testing
    name: r2-friends-cluster
  project: hykuup
  sources:
    - repoURL: https://github.com/notch8/hykuup_knapsack_ops.git
      targetRevision: main
      path: argo/manifests
      ref: ops
    - repoURL: ghcr.io/samvera/charts
      chart: hyrax
      targetRevision: 3.6.0
      helm:
        releaseName: hykuup-knapsack-argo
        valueFiles:
          - $ops/argo/values.yaml
  ignoreDifferences:
    # This secret from the Hyrax chart uses randAlphaNum, which causes
    # a false out-of-sync status. This secret is superseded by our
    # hykuup-app-secrets secret, so we can safely ignore it.
    - group: ""
      kind: Secret
      name: hykuup-knapsack-argo-hyrax
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
# TODO: append Applications for other envs (staging, friends, prod)
