# TODO: delete this file after spinning down "argo" test env
replicaCount: 2

image:
  repository: ghcr.io/notch8/hykuup_knapsack
  tag: 3b5aacd6

resources:
  limits:
    memory: "4Gi"
    cpu: "500m"
  requests:
    memory: "2Gi"
    cpu: "250m"

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

brandingVolume:
  storageClass: efs-sc
derivativesVolume:
  storageClass: efs-sc
uploadsVolume:
  storageClass: efs-sc
  size: 200Gi

imagePullSecrets:
  - name: github

extraVolumeMounts: &volMounts
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/imports
    subPath: imports
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/exports
    subPath: exports
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/public/system
    subPath: public-system
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/public/uploads
    subPath: public-uploads
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/network_files
    subPath: network-files
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/storage/files
    subPath: storage-files
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/log/rack_attack
    subPath: rack-attack

ingress:
  enabled: true
  hosts:
    - host: "hykuup-knapsack-argo.notch8.cloud"
      paths:
        - path: /
    - host: "*.hykuup-knapsack-argo.notch8.cloud"
      paths:
        - path: /
  annotations:
    {
      kubernetes.io/ingress.class: "nginx",
      nginx.ingress.kubernetes.io/proxy-body-size: "0",
      cert-manager.io/cluster-issuer: letsencrypt-production-dns,
    }
  tls:
    - hosts:
        - "hykuup-knapsack-argo.notch8.cloud"
        - "*.hykuup-knapsack-argo.notch8.cloud"
      secretName: hykuup-knapsack-argo-tls

extraEnvFrom: &extraEnvFrom
  - secretRef:
      name: hykuup-app-secrets

extraEnvVars: &envVars
  - name: BUNDLE_LOCAL__HYKU_KNAPSACK
    value: /app/samvera
  - name: BUNDLE_DISABLE_LOCAL_BRANCH_CHECK
    value: "true"
  - name: BUNDLE_BUNDLER_INJECT__GEM_PATH
    value: /app/samvera/bundler.d
  - name: CONFDIR
    value: "/app/samvera/hyrax-webapp/solr/conf"
  - name: DB_ADAPTER
    value: postgresql
  - name: DB_HOST
    value: postgres-postgresql.postgres.svc.cluster.local
  - name: DB_NAME
    value: hykuup-knapsack-argo
  - name: DB_USER
    value: postgres
  - name: FCREPO_BASE_PATH
    value: /hykuup-knapsack-argo
  - name: FCREPO_HOST
    value: fcrepo.fcrepo.svc.cluster.local
  - name: FCREPO_PORT
    value: "8080"
  - name: FCREPO_REST_PATH
    value: rest
  - name: GOOGLE_OAUTH_APP_NAME
    value: hykuup-knapsack-argo
  - name: GOOGLE_OAUTH_APP_VERSION
    value: "1.0"
  - name: GOOGLE_OAUTH_PRIVATE_KEY_PATH
    value: prod-cred.p12
  - name: GOOGLE_OAUTH_CLIENT_EMAIL
    value: hyku-demo@hykuup-knapsack-argo.notch8.cloud
  - name: INITIAL_ADMIN_EMAIL
    value: admin@example.com
  - name: IN_DOCKER
    value: "true"
  - name: LD_LIBRARY_PATH
    value: /app/fits/tools/mediainfo/linux
  - name: PASSENGER_APP_ENV
    value: production
  - name: RAILS_ENV
    value: production
  - name: RAILS_LOG_TO_STDOUT
    value: "true"
  - name: RAILS_MAX_THREADS
    value: "5"
  - name: RAILS_SERVE_STATIC_FILES
    value: "true"
  - name: REDIS_HOST
    value: hykuup-knapsack-argo-redis-master
  - name: HYRAX_ACTIVE_JOB_QUEUE
    value: good_job
  - name: HYRAX_ANALYTICS
    value: "true"
  - name: HYRAX_ANALYTICS_PROVIDER
    value: "ga4"
  - name: HYRAX_FITS_PATH
    value: /app/fits/fits.sh
  - name: HYRAX_VALKYRIE
    value: "true"
  - name: HYKU_ATTACK_RATE_THROTTLE_OFF
    value: "true"
  - name: HYKU_BULKRAX_ENABLED
    value: "true"
  - name: HYKU_BLOCK_VALKYRIE_REDIRECT
    value: "false"
  - name: HYKU_CONTACT_EMAIL
    value: example@hykuup-knapsack-argo.notch8.cloud
  - name: HYKU_CONTACT_EMAIL_TO
    value: example@hykuup-knapsack-argo.notch8.cloud
  - name: HYKU_FILE_ACL
    value: "false"
  - name: HYKU_ADMIN_HOST
    value: hykuup-knapsack-argo.notch8.cloud
  - name: HYKU_ADMIN_ONLY_TENANT_CREATION
    value: "false"
  - name: HYKU_ALLOW_SIGNUP
    value: "false"
  - name: HYKU_DEFAULT_HOST
    value: "%{tenant}.hykuup-knapsack-argo.notch8.cloud"
  - name: HYKU_MULTITENANT
    value: "true"
  - name: HYKU_ROOT_HOST
    value: hykuup-knapsack-argo.notch8.cloud
  - name: SMTP_ADDRESS
    value: "maildev-smtp.maildev.svc.cluster.local"
  - name: SMTP_DOMAIN
    value: "maildev-smtp.maildev.svc.cluster.local"
  - name: SMTP_ENABLED
    value: "true"
  - name: SMTP_PORT
    value: "1025"
  - name: SMTP_TYPE
    value: "plain"
  - name: SMTP_USER_NAME
    value: "admin"
  - name: SMTP_STARTTLS
    value: "false"
  - name: SOLR_ADMIN_USER
    value: admin
  - name: SOLR_COLLECTION_NAME
    value: hykuup-knapsack-argo
  - name: SOLR_CONFIGSET_NAME
    value: hykuup-knapsack-argo
  - name: SOLR_HOST
    value: solr.solr
  - name: SOLR_PORT
    value: "8983"
  - name: SENTRY_ENVIRONMENT
    value: "hykuup-knapsack-argo"
  - name: TEST_USER_EMAIL
    value: user@example.com
  - name: VALKYRIE_ID_TYPE
    value: string
  - name: VALKYRIE_TRANSITION
    value: "true"

worker:
  replicaCount: 1
  image:
    repository: ghcr.io/notch8/hykuup_knapsack/worker
    tag: 3b5aacd6
  extraVolumeMounts: *volMounts
  extraEnvFrom: *extraEnvFrom
  extraEnvVars: *envVars
  podSecurityContext:
    runAsUser: 1001
    runAsGroup: 101
    fsGroup: 101
    fsGroupChangePolicy: "OnRootMismatch"
podSecurityContext:
  runAsUser: 1001
  runAsGroup: 101
  fsGroup: 101
  fsGroupChangePolicy: "OnRootMismatch"

embargoRelease:
  enabled: false
leaseRelease:
  enabled: false

fcrepo:
  enabled: false
postgresql:
  enabled: false
redis:
  enabled: true
  architecture: standalone
  auth:
    existingSecret: hykuup-app-secrets
    existingSecretPasswordKey: REDIS_PASSWORD
solr:
  enabled: false

externalFcrepoHost: fcrepo.fcrepo.svc.cluster.local

externalPostgresql:
  host: postgres-postgresql.postgres.svc.cluster.local
  username: postgres

externalSolrHost: solr.solr.svc.cluster.local
externalSolrUser: admin
externalSolrCollection: "hykuup-knapsack-argo"

fits:
  enabled: true
  servicePort: 8080
  subPath: /fits

global:
  hyraxName: hykuup-knapsack-argo-hyrax

nginx:
  enabled: false
  service:
    port: 80
