apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hykuup-app-secrets
  namespace: hykuup-knapsack-argo
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  data:
    - secretKey: CLIENT_ADMIN_USER_EMAIL
      remoteRef:
        key: hykuup-app-secrets/argo/CLIENT_ADMIN_USER_EMAIL
    - secretKey: CLIENT_ADMIN_USER_PASSWORD
      remoteRef:
        key: hykuup-app-secrets/argo/CLIENT_ADMIN_USER_PASSWORD
    - secretKey: DATABASE_URL
      remoteRef:
        key: hykuup-app-secrets/argo/DATABASE_URL
    - secretKey: DB_PASSWORD
      remoteRef:
        key: hykuup-app-secrets/argo/DB_PASSWORD
    - secretKey: GOOGLE_ANALYTICS_ID
      remoteRef:
        key: hykuup-app-secrets/argo/GOOGLE_ANALYTICS_ID
    - secretKey: GOOGLE_OAUTH_PRIVATE_KEY_SECRET
      remoteRef:
        key: hykuup-app-secrets/argo/GOOGLE_OAUTH_PRIVATE_KEY_SECRET
    - secretKey: GOOGLE_OAUTH_PRIVATE_KEY_VALUE
      remoteRef:
        key: hykuup-app-secrets/argo/GOOGLE_OAUTH_PRIVATE_KEY_VALUE
    - secretKey: INITIAL_ADMIN_PASSWORD
      remoteRef:
        key: hykuup-app-secrets/argo/INITIAL_ADMIN_PASSWORD
    - secretKey: NEGATIVE_CAPTCHA_SECRET
      remoteRef:
        key: hykuup-app-secrets/argo/NEGATIVE_CAPTCHA_SECRET
    - secretKey: RAILS_CACHE_STORE_URL
      remoteRef:
        key: hykuup-app-secrets/argo/RAILS_CACHE_STORE_URL
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: hykuup-app-secrets/argo/REDIS_PASSWORD
    - secretKey: REDIS_URL
      remoteRef:
        key: hykuup-app-secrets/argo/REDIS_URL
    - secretKey: SECRET_KEY_BASE
      remoteRef:
        key: hykuup-app-secrets/argo/SECRET_KEY_BASE
    - secretKey: SENTRY_DSN
      remoteRef:
        key: hykuup-app-secrets/argo/SENTRY_DSN
    - secretKey: SIDEKIQ_REDIS_URL
      remoteRef:
        key: hykuup-app-secrets/argo/SIDEKIQ_REDIS_URL
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: hykuup-app-secrets/argo/SMTP_PASSWORD
    - secretKey: SOLR_ADMIN_PASSWORD
      remoteRef:
        key: hykuup-app-secrets/argo/SOLR_ADMIN_PASSWORD
    - secretKey: SOLR_URL
      remoteRef:
        key: hykuup-app-secrets/argo/SOLR_URL
    - secretKey: TEST_USER_PASSWORD
      remoteRef:
        key: hykuup-app-secrets/argo/TEST_USER_PASSWORD
